version: '2'

networks:
  fabric-ca:

services:

  rca-org0:
    container_name: rca-org0
    image: hyperledger/fabric-ca:latest
    command: /bin/bash -c '/scripts/start-root-ca.sh 2>&1 | tee /data/logs/rca-org0.log'
    environment:
      - FABRIC_CA_SERVER_HOME=/etc/hyperledger/fabric-ca
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_CN=rca-org0
      - FABRIC_CA_SERVER_CSR_HOSTS=rca-org0
      - FABRIC_CA_SERVER_DEBUG=true
      - BOOTSTRAP_USER_PASS=rca-org0-admin:rca-org0-adminpw
      - TARGET_CERTFILE=/data/org0-ca-cert.pem
      - FABRIC_ORGS=org0
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    networks:
      - fabric-ca

  setup:
    container_name: setup
    image: hyperledger/fabric-ca-tools:latest
    command: /bin/bash -c '/scripts/setup-fabric.sh 2>&1 | tee /data/logs/setup.log; sleep 99999'
    volumes:
      - ./scripts:/scripts
      - ./data:/data
    networks:
      - fabric-ca
    depends_on:
      - rca-org0

  orderer1-org0:
    container_name: orderer1-org0
    image: hyperledger/fabric-ca-orderer:latest
    environment:
      - FABRIC_CA_CLIENT_HOME=/etc/hyperledger/orderer
      - FABRIC_CA_CLIENT_TLS_CERTFILES=/data/org0-ca-cert.pem
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - ENROLLMENT_URL=https://orderer1-org0:orderer1-org0pw@rca-org0:7054
      - ORDERER_HOME=/etc/hyperledger/orderer
      - ORDERER_HOST=orderer1-org0
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/data/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=org0MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/data/org0-ca-cert.pem]
      - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_GENERAL_TLS_CLIENTROOTCAS=[/data/org0-ca-cert.pem]
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_DEBUG_BROADCASTTRACEDIR=data/logs
      - ORG=org0
      - ORG_ADMIN_CERT=/data/orgs/org0/msp/admincerts/cert.pem
    command: /bin/bash -c '/scripts/start-orderer.sh 2>&1 | tee /data/logs/orderer1-org0.log'
    volumes:
      - ./scripts:/scripts
      - ./data:/data
      -  /etc/hyperledger/fabric
    networks:
      - fabric-ca
    depends_on:
      - setup 

  
  peer1-org0:
    container_name: peer1-org0
    image: hyperledger/fabric-ca-peer:latest
    environment:
      - FABRIC_CA_CLIENT_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - FABRIC_CA_CLIENT_TLS_CERTFILES=/data/org0-ca-cert.pem
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - ENROLLMENT_URL=https://peer1-org0:peer1-org0pw@rca-org0:7054
      - PEER_NAME=peer1-org0
      - PEER_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - PEER_HOST=peer1-org0
      - PEER_NAME_PASS=peer1-org0:peer1-org0pw
      - CORE_PEER_ID=peer1-org0
      - CORE_PEER_ADDRESS=peer1-org0:7051
      - CORE_PEER_LOCALMSPID=org0MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_fabric-ca
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/data/org0-ca-cert.pem
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/data/org0-ca-cert.pem
      - CORE_PEER_TLS_CLIENTCERT_FILE=/data/tls/peer1-org0-client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/data/tls/peer1-org0-client.key
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1-org0:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - ORG=org0
      - ORG_ADMIN_CERT=/data/orgs/org0/msp/admincerts/cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c '/scripts/start-peer.sh 2>&1 | tee /data/logs/peer1-org0.log'
    volumes:
      - ./scripts:/scripts
      - ./data:/data
      -  /var/run:/host/var/run
      -  /etc/hyperledger/fabric
    networks:
      - fabric-ca
    depends_on:
      - setup  
      - rca-org0
      - orderer1-org0
    ports:
      - 7051:7051
      - 7053:7053
      
  peer2-org0:
    container_name: peer2-org0
    image: hyperledger/fabric-ca-peer:latest
    environment:
      - FABRIC_CA_CLIENT_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - FABRIC_CA_CLIENT_TLS_CERTFILES=/data/org0-ca-cert.pem
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
      - ENROLLMENT_URL=https://peer2-org0:peer2-org0pw@rca-org0:7054
      - PEER_NAME=peer2-org0
      - PEER_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - PEER_HOST=peer2-org0
      - PEER_NAME_PASS=peer2-org0:peer2-org0pw
      - CORE_PEER_ID=peer2-org0
      - CORE_PEER_ADDRESS=peer2-org0:7051
      - CORE_PEER_LOCALMSPID=org0MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_fabric-ca
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/data/org0-ca-cert.pem
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=true
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES=/data/org0-ca-cert.pem
      - CORE_PEER_TLS_CLIENTCERT_FILE=/data/tls/peer2-org0-client.crt
      - CORE_PEER_TLS_CLIENTKEY_FILE=/data/tls/peer2-org0-client.key
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2-org0:7051
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - ORG=org0
      - ORG_ADMIN_CERT=/data/orgs/org0/msp/admincerts/cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash -c '/scripts/start-peer.sh 2>&1 | tee /data/logs/peer2-org0.log'
    volumes:
      - ./scripts:/scripts
      - ./data:/data
      -  /var/run:/host/var/run
    networks:
      - fabric-ca
    depends_on:
      - setup  
      - rca-org0
      - orderer1-org0
    ports:
      - 8051:7051
      - 8053:7053


  run:
    container_name: run
    image: hyperledger/fabric-ca-tools:latest
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric
    command: /bin/bash -c 'sleep 3;/scripts/run-fabric.sh 2>&1 | tee /data/logs/run.log; sleep 99999'
    volumes:
      - ./scripts:/scripts
      - ./data:/data
      - /home/levi/fabric-samples:/opt/gopath/src/github.com/hyperledger/fabric-samples
      - /home/levi/go/src/github.com/hyperledger/fabric:/opt/gopath/src/github.com/hyperledger/fabric
    networks:
      - fabric-ca
    depends_on:
      - orderer1-org0
      - peer1-org0
      - peer2-org0



    


     
 


 

 
